const DB='eduspace_db_v3',V=1;let db,tasks=[],resources=[],taskFilter='all',resourceFilter='all',folder='all';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uid=p=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);
const defs=[['Quizzes','▣','Quiz papers and checked quizzes'],['Assignments','▤','Written and digital assignments'],['Performance Tasks','◆','Performance task files'],['Notes','✎','Your notes and corrections'],['Reviewers','☆','Reviewers for studying'],['Worksheets','□','Practice worksheets'],['Modules','▥','Modules and learning materials']];
function openDB(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,V);r.onupgradeneeded=e=>{let d=e.target.result;if(!d.objectStoreNames.contains('tasks'))d.createObjectStore('tasks',{keyPath:'id'});if(!d.objectStoreNames.contains('resources'))d.createObjectStore('resources',{keyPath:'id'})};r.onsuccess=e=>{db=e.target.result;ok()};r.onerror=()=>no(r.error)})}
function all(n){return new Promise((ok,no)=>{let r=db.transaction(n).objectStore(n).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
function put(n,x){return new Promise((ok,no)=>{let r=db.transaction(n,'readwrite').objectStore(n).put(x);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function del(n,id){return new Promise((ok,no)=>{let r=db.transaction(n,'readwrite').objectStore(n).delete(id);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
function go(p){$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.go===p));scrollTo({top:0,behavior:'smooth'})}
function toast(s,type='normal'){let t=document.createElement('div');t.className='toast '+(type==='success'?'success':'');t.innerHTML=`<span>${type==='success'?'✓':'i'}</span><b>${esc(s)}</b>`;document.body.append(t);setTimeout(()=>t.remove(),1900)}
function date(s){if(!s)return'No due date';return new Date(s+'T00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
async function refresh(){tasks=await all('tasks');resources=await all('resources');tasks.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||b.created-a.created);resources.sort((a,b)=>b.created-a.created);renderHome();renderTasks();renderFolders();renderResources()}
function renderHome(){let d=tasks.filter(x=>x.done).length;$('#total').textContent=tasks.length;$('#todo').textContent=tasks.length-d;$('#done').textContent=d;$('#rcount').textContent=resources.length;$('#status').textContent=tasks.length?`${tasks.length-d} task${tasks.length-d===1?'':'s'} still to do.`:'Your planner is ready.'}
function renderTasks(){let q=$('#taskSearch').value.toLowerCase(),a=tasks.filter(t=>(taskFilter==='all'||(taskFilter==='done'&&t.done)||(taskFilter==='todo'&&!t.done))&&(!q||`${t.title} ${t.subject} ${t.type}`.toLowerCase().includes(q)));$('#tasks').innerHTML=a.map(t=>`<article class="task glass ${t.done?'done':''}"><button class="check ${t.done?'done':''}" data-act="toggle" data-id="${t.id}">${t.done?'✓':''}</button><div><div class="title">${esc(t.title)}</div><div class="meta"><span class="tag">${esc(t.subject||'General')}</span><span class="tag">${esc(t.type||'To-do')}</span><span class="due">${t.due?'Due '+date(t.due):'No due date'}</span></div></div><div class="ra"><button class="small" data-act="editTask" data-id="${t.id}">✎</button><button class="small delete" data-act="delTask" data-id="${t.id}">×</button></div></article>`).join('');$('#taskEmpty').classList.toggle('hidden',a.length>0)}
function customSelect(name,value,options){return `<div class="custom-select" data-select="${name}"><input type="hidden" name="${name}" value="${esc(value)}"><button type="button" class="select-button"><span>${esc(value)}</span><span class="select-arrow">⌄</span></button><div class="select-menu">${options.map(x=>`<button type="button" class="select-option ${x===value?'selected':''}" data-value="${esc(x)}">${esc(x)}${x===value?'<span>✓</span>':''}</button>`).join('')}</div></div>`}
function formatISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function prettyMonth(y,m){return new Date(y,m,1).toLocaleDateString(undefined,{month:'long',year:'numeric'})}
function datePicker(name,value){let base=value?new Date(value+'T00:00'):new Date();return `<div class="date-picker" data-date="${name}" data-value="${esc(value||'')}" data-y="${base.getFullYear()}" data-m="${base.getMonth()}"><input type="hidden" name="${name}" value="${esc(value||'')}"><button type="button" class="date-button"><span>${value?date(value):'Select due date'}</span><span>▣</span></button><div class="calendar-menu">${calendarHTML(base.getFullYear(),base.getMonth(),value)}</div></div>`}
function calendarHTML(y,m,value){let first=new Date(y,m,1),start=first.getDay(),days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate(),cells='';for(let i=0;i<42;i++){let n=i-start+1,day=n,yy=y,mm=m,other=false;if(n<1){day=prevDays+n;mm=m-1;other=true}else if(n>days){day=n-days;mm=m+1;other=true}let iso=formatISO(new Date(yy,mm,day));cells+=`<button type="button" class="cal-day ${other?'muted':''} ${iso===value?'chosen':''}" data-date-value="${iso}">${day}</button>`}return `<div class="cal-head"><button type="button" data-cal="prev">‹</button><strong>${prettyMonth(y,m)}</strong><button type="button" data-cal="next">›</button></div><div class="cal-week"><span>Su</span><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Sa</span></div><div class="cal-grid">${cells}</div><div class="cal-foot"><button type="button" data-cal="clear">Clear</button><button type="button" data-cal="today">Today</button></div>`}
function taskForm(t={}){let edit=!!t.id;show(`<h3>${edit?'Edit task':'Add task'}</h3><p class="sub">Keep an academic task in your planner.</p><form id="tf"><div class="grid"><div class="field full"><label>Task title</label><input name="title" required value="${esc(t.title||'')}" placeholder="e.g. Science worksheet"></div><div class="field"><label>Subject</label><input name="subject" value="${esc(t.subject||'')}" placeholder="e.g. Science"></div><div class="field"><label>Type</label>${customSelect('type',t.type||'Assignment',['Assignment','To-do','Exam','Performance Task'])}</div><div class="field"><label>Due date</label>${datePicker('due',t.due||'')}</div><div class="field full"><label>Details (optional)</label><textarea name="details" placeholder="Add instructions, reminders, or other details...">${esc(t.details||'')}</textarea></div></div><div class="formactions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">${edit?'Save changes':'Add task'}</button></div></form>`);$('#cancel').onclick=close;$('#tf').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),x={id:t.id||uid('task'),title:f.get('title').trim(),subject:f.get('subject').trim(),type:f.get('type'),due:f.get('due'),details:f.get('details').trim(),done:t.done||false,created:t.created||Date.now()};await put('tasks',x);close();await refresh();toast(edit?'Task updated':'Task added','success')}}
async function taskAct(a,id){let t=tasks.find(x=>x.id===id);if(!t)return;if(a==='toggle'){t.done=!t.done;await put('tasks',t);await refresh();toast(t.done?'Task completed':'Task marked as to do','success')}if(a==='editTask')taskForm(t);if(a==='delTask')confirmDelete('Delete this task?','This task will be removed from your Study Planner.',async()=>{await del('tasks',id);await refresh();toast('Task deleted','success')})}
function renderFolders(){$('#folders').innerHTML=defs.map(d=>{let n=resources.filter(r=>r.category===d[0]).length;return`<button class="folder ${folder===d[0]?'active':''}" data-folder="${esc(d[0])}"><div class="foldertop"><span class="foldericon">${d[1]}</span><span class="foldercount">${n}</span></div><strong>${esc(d[0])}</strong><small>${esc(d[2])}</small></button>`}).join('')}
function renderResources(){let q=$('#resSearch').value.toLowerCase(),a=resources.filter(r=>(!q||`${r.title} ${r.subject} ${r.category} ${r.notebook}`.toLowerCase().includes(q))&&(folder==='all'||r.category===folder)&&(resourceFilter==='all'||r.category===resourceFilter));$('#resourcesList').innerHTML=a.map(r=>`<article class="resource glass"><div class="thumb">${r.image?`<img src="${r.image}" alt="Saved paper">`:'▤'}</div><div><strong>${esc(r.title)}</strong><div class="meta"><span class="tag">${esc(r.category)}</span><span class="tag">${esc(r.subject||'General')}</span></div><p>${esc(r.notebook||'No notebook text yet.')}</p></div><div class="ra"><button class="small" data-act="viewRes" data-id="${r.id}">↗</button><button class="small" data-act="editRes" data-id="${r.id}">✎</button><button class="small delete" data-act="delRes" data-id="${r.id}">×</button></div></article>`).join('');$('#resEmpty').classList.toggle('hidden',a.length>0)}
function imageData(file){return new Promise((ok,no)=>{let r=new FileReader();r.onload=()=>{let i=new Image();i.onload=()=>{let s=Math.min(1,1400/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=i.width*s;c.height=i.height*s;c.getContext('2d').drawImage(i,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};i.onerror=no;i.src=r.result};r.onerror=no;r.readAsDataURL(file)})}
function resForm(r={}){let edit=!!r.id;show(`<h3>${edit?'Edit resource':'Add resource'}</h3><p class="sub">Save a school paper photo and a separate digital notebook for your own writing.</p><form id="rf"><div class="grid"><div class="field full"><label>Resource title</label><input name="title" required value="${esc(r.title||'')}" placeholder="e.g. Science Quiz 1"></div><div class="field"><label>Folder</label>${customSelect('category',r.category||'Quizzes',defs.map(d=>d[0]))}</div><div class="field"><label>Subject</label><input name="subject" value="${esc(r.subject||'')}" placeholder="e.g. Science"></div><div class="field full"><label>Photo backup of school paper <span class="optional">optional</span></label><label for="photo" class="upload-btn">＋ Upload photo</label><input id="photo" class="file-input" type="file" accept="image/*" capture="environment"><span class="file">You can upload or take a photo of an already-checked paper. It is saved locally on this device.</span>${r.image?`<img class="preview" src="${r.image}" alt="Current paper">`:''}</div><div class="field full"><label>Digital notebook</label><textarea name="notebook" placeholder="Type your answers, solutions, corrections, notes, or reminders here...">${esc(r.notebook||'')}</textarea></div></div><div class="formactions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">${edit?'Save changes':'Save resource'}</button></div></form>`);let img=r.image||'';$('#photo').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.size>7*1024*1024){toast('Please choose an image under 7 MB.');e.target.value='';return}try{img=await imageData(f);toast('Photo added','success')}catch{toast('Could not read that photo.')}};$('#cancel').onclick=close;$('#rf').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),x={id:r.id||uid('res'),title:f.get('title').trim(),category:f.get('category'),subject:f.get('subject').trim(),image:img,notebook:f.get('notebook').trim(),created:r.created||Date.now()};await put('resources',x);close();await refresh();toast(edit?'Resource updated':'Resource saved','success')}}
function viewRes(r){show(`<h3>${esc(r.title)}</h3><p class="sub">${esc(r.category)} · ${esc(r.subject||'General')}</p>${r.image?`<img class="preview" src="${r.image}" alt="Saved paper">`:'<div class="empty" style="padding:25px">No photo backup saved.</div>'}<div class="notebook"><div class="notebookhead"><strong>Digital Notebook</strong><span>Saved locally</span></div><div class="notebookcontent">${esc(r.notebook||'No notebook text yet.')}</div></div><div class="formactions"><button class="primary" id="ve">Edit resource</button></div>`);$('#ve').onclick=()=>resForm(r)}
async function resAct(a,id){let r=resources.find(x=>x.id===id);if(!r)return;if(a==='viewRes')viewRes(r);if(a==='editRes')resForm(r);if(a==='delRes')confirmDelete('Delete this resource?','This resource and its saved photo will be removed from this device.',async()=>{await del('resources',id);await refresh();toast('Resource deleted','success')})}
function show(html){$('#modal').innerHTML=html;$('#backdrop').classList.remove('hidden');document.body.style.overflow='hidden'}
function close(){$('#backdrop').classList.add('hidden');document.body.style.overflow=''}
function confirmDelete(title,text,action){show(`<div class="confirm-box"><div class="confirm-icon">×</div><h3>${esc(title)}</h3><p class="sub">${esc(text)}</p><div class="formactions"><button class="secondary" id="confirmCancel">Cancel</button><button class="danger-btn" id="confirmOK">Delete</button></div></div>`);$('#confirmCancel').onclick=close;$('#confirmOK').onclick=async()=>{close();await action()}}
document.addEventListener('click',e=>{
 let g=e.target.closest('[data-go]');if(g){go(g.dataset.go);return}
 let a=e.target.closest('[data-act]');if(a){if(['toggle','editTask','delTask'].includes(a.dataset.act))taskAct(a.dataset.act,a.dataset.id);else resAct(a.dataset.act,a.dataset.id);return}
 let f=e.target.closest('[data-folder]');if(f){folder=folder===f.dataset.folder?'all':f.dataset.folder;resourceFilter='all';$$('[data-rf]').forEach(x=>x.classList.toggle('active',x.dataset.rf==='all'));renderFolders();renderResources();return}
 let rf=e.target.closest('[data-rf]');if(rf){resourceFilter=rf.dataset.rf;folder='all';$$('[data-rf]').forEach(x=>x.classList.toggle('active',x===rf));renderFolders();renderResources();return}
 let sb=e.target.closest('.select-button');if(sb){let box=sb.closest('.custom-select');$$('.custom-select.open').forEach(x=>{if(x!==box)x.classList.remove('open')});box.classList.toggle('open');return}
 let opt=e.target.closest('.select-option');if(opt){let box=opt.closest('.custom-select'),val=opt.dataset.value;box.querySelector('input[type=hidden]').value=val;box.querySelector('.select-button span').textContent=val;box.querySelectorAll('.select-option').forEach(x=>{x.classList.toggle('selected',x===opt);x.innerHTML=esc(x.dataset.value)+(x===opt?'<span>✓</span>':'' )});box.classList.remove('open');return}
 let dbtn=e.target.closest('.date-button');if(dbtn){let box=dbtn.closest('.date-picker');$$('.date-picker.open').forEach(x=>{if(x!==box)x.classList.remove('open')});box.classList.toggle('open');return}
 let cal=e.target.closest('[data-cal]');if(cal){let box=cal.closest('.date-picker'),y=+box.dataset.y,m=+box.dataset.m;if(cal.dataset.cal==='prev')m--;if(cal.dataset.cal==='next')m++;if(m<0){m=11;y--}if(m>11){m=0;y++}if(cal.dataset.cal==='clear'){box.dataset.value='';box.querySelector('input').value='';box.querySelector('.date-button span').textContent='Select due date';box.classList.remove('open');return}if(cal.dataset.cal==='today'){let now=new Date();y=now.getFullYear();m=now.getMonth();let iso=formatISO(now);box.dataset.value=iso;box.querySelector('input').value=iso;box.querySelector('.date-button span').textContent=date(iso)}box.dataset.y=y;box.dataset.m=m;box.querySelector('.calendar-menu').innerHTML=calendarHTML(y,m,box.dataset.value);return}
 let day=e.target.closest('.cal-day');if(day){let box=day.closest('.date-picker'),iso=day.dataset.dateValue;box.dataset.value=iso;box.querySelector('input').value=iso;box.querySelector('.date-button span').textContent=date(iso);box.classList.remove('open');return}
});
document.addEventListener('click',e=>{if(!e.target.closest('.custom-select'))$$('.custom-select.open').forEach(x=>x.classList.remove('open'));if(!e.target.closest('.date-picker'))$$('.date-picker.open').forEach(x=>x.classList.remove('open'))});
$('#addTask').onclick=()=>taskForm();$('#addResource').onclick=()=>resForm();$('#taskSearch').oninput=renderTasks;$('#resSearch').oninput=renderResources;$$('#taskFilter button').forEach(b=>b.onclick=()=>{$$('#taskFilter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');taskFilter=b.dataset.f;renderTasks()});$('#close').onclick=close;$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')close()};$('#theme').onclick=()=>{let light=!document.body.classList.contains('light');document.body.classList.toggle('light',light);document.documentElement.classList.toggle('light',light);localStorage.setItem('ed_theme',light?'light':'dark');$('#theme').textContent=light?'☀':'☾'};if(localStorage.getItem('ed_theme')==='light'){document.body.classList.add('light');document.documentElement.classList.add('light')}$('#theme').textContent=document.body.classList.contains('light')?'☀':'☾';
(async()=>{try{await openDB();await refresh();go('home')}catch(e){toast('EDUSPACE could not open local storage in this browser.')}})();
